package com.recipe_manager.model.entity.recipe;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class RecipeIngredientIdTest {

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    RecipeIngredientId id = new RecipeIngredientId(1L, 2L);
    assertThat(id.getRecipeId()).isEqualTo(1L);
    assertThat(id.getIngredientId()).isEqualTo(2L);
  }

  @Test
  @DisplayName("No-args constructor sets nulls")
  @Tag("standard-processing")
  void noArgsConstructorSetsDefaults() {
    RecipeIngredientId id = new RecipeIngredientId();
    assertThat(id.getRecipeId()).isNull();
    assertThat(id.getIngredientId()).isNull();
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    RecipeIngredientId id = new RecipeIngredientId();
    id.setRecipeId(5L);
    id.setIngredientId(6L);
    assertThat(id.getRecipeId()).isEqualTo(5L);
    assertThat(id.getIngredientId()).isEqualTo(6L);
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    RecipeIngredientId id1 = RecipeIngredientId.builder().recipeId(1L).ingredientId(2L).build();
    RecipeIngredientId id2 = RecipeIngredientId.builder().recipeId(1L).ingredientId(2L).build();
    assertThat(id1).isEqualTo(id2);
    assertThat(id1.hashCode()).isEqualTo(id2.hashCode());
    assertThat(id1.toString()).contains("1");
  }
}
