---
ci:
  autofix_commit_msg: |
    chore(pre-commit-ci): auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: 'chore(pre-commit-ci): pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip:
    # Skip local Maven hooks - require Java/Maven and system dependencies
    - maven-checkstyle
    - maven-spotbugs
    - maven-pmd
    - spotless-apply
    - sortpom-sort
    - sortpom-verify
    # Skip system-dependent hooks
    - kube-score
    - trufflehog
  submodules: false

repos:
  # File formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml, json, xml]
        additional_dependencies: [prettier-plugin-xml]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict]


  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: [--severity=warning]


  # Conventional commits validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict, --verbose]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: detect-private-key

  # Enhanced secret detection
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.90.8
    hooks:
      - id: trufflehog
        name: TruffleHog Secret Detection
        entry: trufflehog git file://. --since-commit HEAD --only-verified --fail
        language: system
        stages: [pre-commit, pre-push]

  # Docker security scanning
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        name: Dockerfile Security Scan
        args: ['--ignore', 'DL3008', '--ignore', 'DL3009']

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: Markdown Linting
        args: ['--fix']

  # Maven specific checks
  - repo: local
    hooks:
      - id: maven-checkstyle
        name: Maven Checkstyle
        entry: mvn
        language: system
        pass_filenames: false
        always_run: true
        args: ['checkstyle:check']
        types: [java]

      - id: maven-spotbugs
        name: Maven SpotBugs
        entry: mvn
        language: system
        pass_filenames: false
        always_run: true
        args: ['spotbugs:check']
        types: [java]

      - id: maven-pmd
        name: Maven PMD
        entry: mvn
        language: system
        pass_filenames: false
        always_run: true
        args: ['pmd:check']
        types: [java]


      - id: spotless-apply
        name: spotless-apply
        entry: mvn
        args: ['spotless:apply']
        language: system
        pass_filenames: false
        always_run: true
        types: [java]

      - id: sortpom-sort
        name: sortpom-sort
        entry: mvn
        args: ['sortpom:sort']
        language: system
        pass_filenames: false
        always_run: true
        files: pom.xml

      - id: sortpom-verify
        name: sortpom-verify
        entry: mvn
        args: ['sortpom:verify']
        language: system
        pass_filenames: false
        always_run: true
        files: pom.xml

      - id: kube-score
        name: kube-score
        entry: >-
          sh -c 'find k8s -name "*.yaml" -type f -not -path "*/templates/*" |
          xargs kube-score score'
        language: system
        files: k8s/.*\.yaml$
        pass_filenames: false
        args: []
