package com.recipe_manager.model.dto.media;

import static org.assertj.core.api.Assertions.*;

import java.time.LocalDateTime;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class RecipeTagMediaDtoTest {

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    LocalDateTime now = LocalDateTime.now();
    RecipeTagMediaDto dto = RecipeTagMediaDto.builder()
        .mediaId(1L)
        .url("url")
        .altText("alt")
        .contentType("type")
        .fileSize(123L)
        .createdAt(now)
        .updatedAt(now)
        .recipeId(2L)
        .tagId(3L)
        .build();
    assertThat(dto.getMediaId()).isEqualTo(1L);
    assertThat(dto.getRecipeId()).isEqualTo(2L);
    assertThat(dto.getTagId()).isEqualTo(3L);
    assertThat(dto.getUrl()).isEqualTo("url");
    assertThat(dto.getAltText()).isEqualTo("alt");
    assertThat(dto.getContentType()).isEqualTo("type");
    assertThat(dto.getFileSize()).isEqualTo(123L);
    assertThat(dto.getCreatedAt()).isEqualTo(now);
    assertThat(dto.getUpdatedAt()).isEqualTo(now);
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    RecipeTagMediaDto dto = new RecipeTagMediaDto();
    dto.setTagId(5L);
    assertThat(dto.getTagId()).isEqualTo(5L);
    dto.setRecipeId(6L);
    assertThat(dto.getRecipeId()).isEqualTo(6L);
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    RecipeTagMediaDto dto1 = RecipeTagMediaDto.builder().mediaId(1L).tagId(2L).build();
    RecipeTagMediaDto dto2 = RecipeTagMediaDto.builder().mediaId(1L).tagId(2L).build();
    assertThat(dto1).isEqualTo(dto2);
    assertThat(dto1.hashCode()).isEqualTo(dto2.hashCode());
    assertThat(dto1.toString()).contains("tagId=2");
  }

  @Test
  @DisplayName("Null handling for all fields")
  @Tag("error-processing")
  void nullHandlingForAllFields() {
    RecipeTagMediaDto dto = RecipeTagMediaDto.builder().build();
    assertThat(dto.getMediaId()).isNull();
    assertThat(dto.getRecipeId()).isNull();
    assertThat(dto.getTagId()).isNull();
    assertThat(dto.getUrl()).isNull();
    assertThat(dto.getAltText()).isNull();
    assertThat(dto.getContentType()).isNull();
    assertThat(dto.getFileSize()).isNull();
    assertThat(dto.getCreatedAt()).isNull();
    assertThat(dto.getUpdatedAt()).isNull();
  }
}
