package com.recipe_manager.model.dto.media;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDateTime;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class RecipeFavoriteMediaDtoTest {

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    LocalDateTime now = LocalDateTime.now();
    RecipeFavoriteMediaDto dto = RecipeFavoriteMediaDto.builder()
        .mediaId(1L)
        .url("url")
        .altText("alt")
        .contentType("type")
        .fileSize(123L)
        .createdAt(now)
        .updatedAt(now)
        .recipeId(2L)
        .userId("user")
        .build();
    assertThat(dto.getMediaId()).isEqualTo(1L);
    assertThat(dto.getRecipeId()).isEqualTo(2L);
    assertThat(dto.getUserId()).isEqualTo("user");
    assertThat(dto.getUrl()).isEqualTo("url");
    assertThat(dto.getAltText()).isEqualTo("alt");
    assertThat(dto.getContentType()).isEqualTo("type");
    assertThat(dto.getFileSize()).isEqualTo(123L);
    assertThat(dto.getCreatedAt()).isEqualTo(now);
    assertThat(dto.getUpdatedAt()).isEqualTo(now);
  }

  @Test
  @DisplayName("Builder sets fields and uses defaults")
  @Tag("standard-processing")
  void builderSetsFieldsAndDefaults() {
    RecipeFavoriteMediaDto dto = RecipeFavoriteMediaDto.builder().mediaId(1L).recipeId(2L).userId("user").build();
    assertThat(dto.getMediaId()).isEqualTo(1L);
    assertThat(dto.getRecipeId()).isEqualTo(2L);
    assertThat(dto.getUserId()).isEqualTo("user");
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    RecipeFavoriteMediaDto dto = new RecipeFavoriteMediaDto();
    dto.setUserId("u");
    assertThat(dto.getUserId()).isEqualTo("u");
    dto.setRecipeId(6L);
    assertThat(dto.getRecipeId()).isEqualTo(6L);
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    RecipeFavoriteMediaDto dto1 = RecipeFavoriteMediaDto.builder().mediaId(1L).userId("u").build();
    RecipeFavoriteMediaDto dto2 = RecipeFavoriteMediaDto.builder().mediaId(1L).userId("u").build();
    assertThat(dto1).isEqualTo(dto2);
    assertThat(dto1.hashCode()).isEqualTo(dto2.hashCode());
    assertThat(dto1.toString()).contains("userId=u");
  }

  @Test
  @DisplayName("Null handling for all fields")
  @Tag("error-processing")
  void nullHandlingForAllFields() {
    RecipeFavoriteMediaDto dto = new RecipeFavoriteMediaDto();
    assertThat(dto.getMediaId()).isNull();
    assertThat(dto.getRecipeId()).isNull();
    assertThat(dto.getUserId()).isNull();
    assertThat(dto.getUrl()).isNull();
    assertThat(dto.getAltText()).isNull();
    assertThat(dto.getContentType()).isNull();
    assertThat(dto.getFileSize()).isNull();
    assertThat(dto.getCreatedAt()).isNull();
    assertThat(dto.getUpdatedAt()).isNull();
  }
}
