---
labels: [idea]
body:
  - type: markdown
    attributes:
      value: |
        Share your ideas for new features or improvements to the OAuth2 Auth Service!

  - type: textarea
    attributes:
      label: Idea Description
      description: Describe your idea
      placeholder: What would you like to see?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem or Use Case
      description: What problem does this solve or what use case does it enable?
      placeholder: This would help with...

  - type: textarea
    attributes:
      label: Proposed Solution
      description: How might this be implemented?
      placeholder: Any thoughts on implementation?

  - type: textarea
    attributes:
      label: Additional Context
      description: Any additional information
      placeholder: Links, examples, mockups, etc.
