---
# Production environment overrides
spring:
  datasource:
    url: jdbc:postgresql://prod-db:5432/recipe_db
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: INFO
    org.springframework.web: WARN
