---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recipe-manager-config
  namespace: default
  labels:
    app: recipe-manager-service
data:
  db_host: ${DB_HOST}
  db_name: ${DB_NAME}
  db_user: ${DB_USER}
  db_schema: ${DB_SCHEMA}
