---
# k8s/configmap-template.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: recipe-manager-config
  namespace: recipe-manager
  labels:
    app: recipe-manager-service
data:
  POSTGRES_HOST: '${POSTGRES_HOST}'
  POSTGRES_PORT: '${POSTGRES_PORT}'
  POSTGRES_DB: '${POSTGRES_DB}'
  POSTGRES_SCHEMA: '${POSTGRES_SCHEMA}'
  RECIPE_MANAGEMENT_DB_USER: '${RECIPE_MANAGEMENT_DB_USER}'
  # OAuth2 Service Configuration
  OAUTH2_SERVICE_BASE_URL: '${OAUTH2_SERVICE_BASE_URL}'
  OAUTH2_SERVICE_ENABLED: '${OAUTH2_SERVICE_ENABLED}'
  OAUTH2_SERVICE_TO_SERVICE_ENABLED: '${OAUTH2_SERVICE_TO_SERVICE_ENABLED}'
  OAUTH2_SERVICE_TIMEOUT: '${OAUTH2_SERVICE_TIMEOUT}'
  OAUTH2_CLIENT_ID: '${OAUTH2_CLIENT_ID}'
  OAUTH2_INTROSPECTION_ENABLED: '${OAUTH2_INTROSPECTION_ENABLED}'
  OAUTH2_SCOPES: '${OAUTH2_SCOPES}'
  OAUTH2_TOKEN_PATH: '${OAUTH2_TOKEN_PATH}'
  OAUTH2_INTROSPECTION_PATH: '${OAUTH2_INTROSPECTION_PATH}'
  OAUTH2_USERINFO_PATH: '${OAUTH2_USERINFO_PATH}'
