---
name: Feature Request
description: Suggest a new feature or enhancement for the recipe management service
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - jsamuelsen
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand
        and evaluate your proposal.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: A clear description of the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: Describe any alternative solutions or workarounds

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which area does this feature affect?
      options:
        - Recipe Management
        - Ingredient Management
        - Shopping List
        - API/REST Endpoints
        - Database Schema
        - Authentication/Authorization
        - Data Validation
        - Search/Filtering
        - Performance Optimization
        - Documentation
        - Testing
        - DevOps/Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking production use)
        - High (Significantly improves usability)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be valuable
      placeholder: |
        As a [user type], I want to [goal] so that [benefit].
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: API Design (if applicable)
      description: Proposed API endpoints, request/response formats, or method signatures
      placeholder: |
        GET /api/v1/recipes/{id}/ingredients
        Response: { "ingredients": [...] }
      render: yaml

  - type: checkboxes
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature may introduce breaking changes
          required: false
        - label: I have considered backward compatibility
          required: false

  - type: textarea
    id: breaking_details
    attributes:
      label: Breaking Changes Details
      description: If this introduces breaking changes, describe them and potential migration paths
      placeholder: Describe breaking changes and how users can migrate

  - type: checkboxes
    id: security
    attributes:
      label: Security Implications
      description: Does this feature have security considerations?
      options:
        - label: This feature may have security implications
          required: false
        - label: This feature requires authentication/authorization changes
          required: false
        - label: This feature handles sensitive data
          required: false

  - type: textarea
    id: security_details
    attributes:
      label: Security Considerations
      description: Describe any security implications or requirements
      placeholder: Authentication, data privacy, input validation, etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: Screenshots, diagrams, code examples, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing feature requests to avoid duplicates
          required: true
        - label: I have described the problem and proposed solution clearly
          required: true
        - label: I have considered the impact on existing functionality
          required: true
