---
name: Security Vulnerability
description: >-
  Report a LOW severity security issue
  (use GitHub Security Advisories for critical issues!)
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees:
  - jsamuelsen
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT: Critical Security Vulnerabilities

        **DO NOT use this template for critical or high-severity
        security issues!**

        For critical security vulnerabilities, please use
        [GitHub Security Advisories](
        https://github.com/Recipe-Web-App/recipe-management-service/security/advisories/new
        ) to report privately.

        This template is ONLY for **LOW severity** security issues
        that can be discussed publicly.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: What is the severity of this security issue?
      options:
        - Low (Best practice violation, minor information disclosure)
        - Medium (Limited information disclosure, minor security misconfiguration)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **If you selected anything other than "Low", STOP and use
        [Security Advisories](
        https://github.com/Recipe-Web-App/recipe-management-service/security/advisories/new
        ) instead!**

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Clear description of the security issue
      placeholder: Describe the security concern
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Information Disclosure (minimal impact)
        - Security Header Missing
        - Verbose Error Messages
        - Dependency Vulnerability (low severity)
        - Configuration Best Practice
        - Input Validation (non-critical)
        - Logging Sensitive Data
        - TLS/SSL Configuration
        - CORS Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker potentially achieve?
      placeholder: Describe the potential security impact
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this issue be reproduced? (only if safe to disclose publicly)
      placeholder: |
        1. Configure service with...
        2. Send request to...
        3. Observe...

  - type: textarea
    id: affected
    attributes:
      label: Affected Components
      description: Which components are affected?
      placeholder: |
        - Component 1
        - Component 2

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this issue?
      placeholder: Proposed security improvements or configuration changes

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      value: |
        - Version:
        - Deployment:
        - Configuration:

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Confirm responsible disclosure practices
      options:
        - label: I confirm this is a LOW severity issue appropriate for public disclosure
          required: true
        - label: I have NOT disclosed this vulnerability publicly elsewhere
          required: true
        - label: I understand critical issues should use Security Advisories
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Additional details, references, etc.
