package com.recipe_manager.model.entity.collection;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.UUID;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class CollectionFavoriteIdTest {

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    UUID userId = UUID.randomUUID();
    CollectionFavoriteId id = new CollectionFavoriteId(userId, 1L);
    assertThat(id.getUserId()).isEqualTo(userId);
    assertThat(id.getCollectionId()).isEqualTo(1L);
  }

  @Test
  @DisplayName("No-args constructor sets nulls")
  @Tag("standard-processing")
  void noArgsConstructorSetsDefaults() {
    CollectionFavoriteId id = new CollectionFavoriteId();
    assertThat(id.getUserId()).isNull();
    assertThat(id.getCollectionId()).isNull();
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    CollectionFavoriteId id = new CollectionFavoriteId();
    UUID userId = UUID.randomUUID();
    id.setUserId(userId);
    id.setCollectionId(2L);
    assertThat(id.getUserId()).isEqualTo(userId);
    assertThat(id.getCollectionId()).isEqualTo(2L);
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    UUID userId = UUID.randomUUID();
    CollectionFavoriteId id1 =
        CollectionFavoriteId.builder().userId(userId).collectionId(1L).build();
    CollectionFavoriteId id2 =
        CollectionFavoriteId.builder().userId(userId).collectionId(1L).build();
    assertThat(id1).isEqualTo(id2);
    assertThat(id1.hashCode()).isEqualTo(id2.hashCode());
    assertThat(id1.toString()).contains(userId.toString());
  }
}
