package com.recipe_manager.model.entity.collection;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDateTime;
import java.util.UUID;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class CollectionFavoriteTest {

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    UUID userId = UUID.randomUUID();
    CollectionFavoriteId id = new CollectionFavoriteId(userId, 1L);
    RecipeCollection collection = new RecipeCollection();
    LocalDateTime now = LocalDateTime.now();
    CollectionFavorite fav = new CollectionFavorite(id, collection, now);
    assertThat(fav.getId()).isEqualTo(id);
    assertThat(fav.getCollection()).isSameAs(collection);
    assertThat(fav.getId().getUserId()).isEqualTo(userId); // Access through embedded ID
    assertThat(fav.getFavoritedAt()).isEqualTo(now);
  }

  @Test
  @DisplayName("No-args constructor sets nulls")
  @Tag("standard-processing")
  void noArgsConstructorSetsDefaults() {
    CollectionFavorite fav = new CollectionFavorite();
    assertThat(fav.getId()).isNull();
    assertThat(fav.getCollection()).isNull();
    assertThat(fav.getFavoritedAt()).isNull();
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    CollectionFavorite fav = new CollectionFavorite();
    CollectionFavoriteId id = new CollectionFavoriteId();
    id.setUserId(UUID.randomUUID());
    fav.setId(id);
    assertThat(fav.getId().getUserId()).isNotNull();
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    CollectionFavoriteId id = new CollectionFavoriteId(UUID.randomUUID(), 1L);
    CollectionFavorite f1 = CollectionFavorite.builder().id(id).build();
    CollectionFavorite f2 = CollectionFavorite.builder().id(id).build();
    assertThat(f1).isEqualTo(f2);
    assertThat(f1.hashCode()).isEqualTo(f2.hashCode());
    assertThat(f1.toString()).contains("CollectionFavorite");
  }
}
