package com.recipe_manager.model.dto.response;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

import com.recipe_manager.model.dto.recipe.RecipeCommentDto;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class RecipeCommentsResponseTest {

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    RecipeCommentDto comment =
        RecipeCommentDto.builder().commentId(1L).commentText("Test comment").build();
    List<RecipeCommentDto> comments = Arrays.asList(comment);

    RecipeCommentsResponse response = new RecipeCommentsResponse(123L, comments);

    assertThat(response.getRecipeId()).isEqualTo(123L);
    assertThat(response.getComments()).isEqualTo(comments);
  }

  @Test
  @DisplayName("No-args constructor sets defaults and nulls")
  @Tag("standard-processing")
  void noArgsConstructorSetsDefaults() {
    RecipeCommentsResponse response = new RecipeCommentsResponse();

    assertThat(response.getRecipeId()).isNull();
    assertThat(response.getComments()).isNull();
  }

  @Test
  @DisplayName("Builder sets fields and uses defaults")
  @Tag("standard-processing")
  void builderSetsFieldsAndDefaults() {
    RecipeCommentDto comment =
        RecipeCommentDto.builder().commentId(1L).commentText("Test comment").build();
    List<RecipeCommentDto> comments = Arrays.asList(comment);

    RecipeCommentsResponse response =
        RecipeCommentsResponse.builder().recipeId(123L).comments(comments).build();

    assertThat(response.getRecipeId()).isEqualTo(123L);
    assertThat(response.getComments()).isEqualTo(comments);
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    RecipeCommentsResponse response = new RecipeCommentsResponse();

    response.setRecipeId(789L);
    assertThat(response.getRecipeId()).isEqualTo(789L);

    RecipeCommentDto comment =
        RecipeCommentDto.builder().commentId(2L).commentText("Another comment").build();
    List<RecipeCommentDto> comments = Arrays.asList(comment);
    response.setComments(comments);
    assertThat(response.getComments()).isEqualTo(comments);
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    RecipeCommentDto comment =
        RecipeCommentDto.builder().commentId(1L).commentText("Test comment").build();
    List<RecipeCommentDto> comments = Arrays.asList(comment);

    RecipeCommentsResponse response1 =
        RecipeCommentsResponse.builder().recipeId(123L).comments(comments).build();
    RecipeCommentsResponse response2 =
        RecipeCommentsResponse.builder().recipeId(123L).comments(comments).build();

    assertThat(response1).isEqualTo(response2);
    assertThat(response1.hashCode()).isEqualTo(response2.hashCode());
    assertThat(response1.toString()).contains("123");
  }

  @Test
  @DisplayName("Null handling for all fields")
  @Tag("error-processing")
  void nullHandlingForAllFields() {
    RecipeCommentsResponse response = RecipeCommentsResponse.builder().build();

    assertThat(response.getRecipeId()).isNull();
    assertThat(response.getComments()).isNull();
  }

  @Test
  @DisplayName("Empty comments list is handled correctly")
  @Tag("standard-processing")
  void emptyCommentsListHandledCorrectly() {
    RecipeCommentsResponse response =
        RecipeCommentsResponse.builder().recipeId(123L).comments(Collections.emptyList()).build();

    assertThat(response.getComments()).isEmpty();
    assertThat(response.getRecipeId()).isEqualTo(123L);
  }

  @Test
  @DisplayName("Multiple comments are handled correctly")
  @Tag("standard-processing")
  void multipleCommentsHandledCorrectly() {
    RecipeCommentDto comment1 =
        RecipeCommentDto.builder()
            .commentId(1L)
            .recipeId(123L)
            .userId(UUID.randomUUID())
            .commentText("First comment")
            .isPublic(true)
            .createdAt(LocalDateTime.now())
            .build();

    RecipeCommentDto comment2 =
        RecipeCommentDto.builder()
            .commentId(2L)
            .recipeId(123L)
            .userId(UUID.randomUUID())
            .commentText("Second comment")
            .isPublic(false)
            .createdAt(LocalDateTime.now())
            .build();

    List<RecipeCommentDto> comments = Arrays.asList(comment1, comment2);

    RecipeCommentsResponse response =
        RecipeCommentsResponse.builder().recipeId(123L).comments(comments).build();

    assertThat(response.getComments()).hasSize(2);
    assertThat(response.getComments()).containsExactly(comment1, comment2);
    assertThat(response.getComments().get(0).getCommentText()).isEqualTo("First comment");
    assertThat(response.getComments().get(1).getCommentText()).isEqualTo("Second comment");
  }
}
