package com.recipe_manager.model.dto.request;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Set;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class AddRecipeCommentRequestTest {

  private Validator validator;

  @BeforeEach
  void setUp() {
    ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
    validator = factory.getValidator();
  }

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    AddRecipeCommentRequest request = new AddRecipeCommentRequest("Test comment", true);

    assertThat(request.getCommentText()).isEqualTo("Test comment");
    assertThat(request.getIsPublic()).isTrue();
  }

  @Test
  @DisplayName("No-args constructor sets defaults and nulls")
  @Tag("standard-processing")
  void noArgsConstructorSetsDefaults() {
    AddRecipeCommentRequest request = new AddRecipeCommentRequest();

    assertThat(request.getCommentText()).isNull();
    assertThat(request.getIsPublic()).isTrue(); // Default value from @Builder.Default
  }

  @Test
  @DisplayName("Builder sets fields and uses defaults")
  @Tag("standard-processing")
  void builderSetsFieldsAndDefaults() {
    AddRecipeCommentRequest request =
        AddRecipeCommentRequest.builder().commentText("Test comment").build();

    assertThat(request.getCommentText()).isEqualTo("Test comment");
    assertThat(request.getIsPublic()).isTrue(); // Default value
  }

  @Test
  @DisplayName("Builder allows setting isPublic to false")
  @Tag("standard-processing")
  void builderAllowsSettingIsPublicToFalse() {
    AddRecipeCommentRequest request =
        AddRecipeCommentRequest.builder().commentText("Private comment").isPublic(false).build();

    assertThat(request.getCommentText()).isEqualTo("Private comment");
    assertThat(request.getIsPublic()).isFalse();
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    AddRecipeCommentRequest request = new AddRecipeCommentRequest();

    request.setCommentText("New comment");
    request.setIsPublic(false);

    assertThat(request.getCommentText()).isEqualTo("New comment");
    assertThat(request.getIsPublic()).isFalse();
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    AddRecipeCommentRequest request1 =
        AddRecipeCommentRequest.builder().commentText("Same comment").isPublic(true).build();
    AddRecipeCommentRequest request2 =
        AddRecipeCommentRequest.builder().commentText("Same comment").isPublic(true).build();

    assertThat(request1).isEqualTo(request2);
    assertThat(request1.hashCode()).isEqualTo(request2.hashCode());
    assertThat(request1.toString()).contains("Same comment");
  }

  @Test
  @DisplayName("Valid comment passes validation")
  @Tag("standard-processing")
  void validCommentPassesValidation() {
    AddRecipeCommentRequest request =
        AddRecipeCommentRequest.builder().commentText("This is a valid comment").build();

    Set<ConstraintViolation<AddRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).isEmpty();
  }

  @Test
  @DisplayName("Null comment fails validation")
  @Tag("error-processing")
  void nullCommentFailsValidation() {
    AddRecipeCommentRequest request = AddRecipeCommentRequest.builder().commentText(null).build();

    Set<ConstraintViolation<AddRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).hasSize(1);
    assertThat(violations.iterator().next().getMessage()).isEqualTo("Comment text cannot be blank");
  }

  @Test
  @DisplayName("Empty comment fails validation")
  @Tag("error-processing")
  void emptyCommentFailsValidation() {
    AddRecipeCommentRequest request = AddRecipeCommentRequest.builder().commentText("").build();

    Set<ConstraintViolation<AddRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).hasSize(1);
    assertThat(violations.iterator().next().getMessage()).isEqualTo("Comment text cannot be blank");
  }

  @Test
  @DisplayName("Blank comment fails validation")
  @Tag("error-processing")
  void blankCommentFailsValidation() {
    AddRecipeCommentRequest request =
        AddRecipeCommentRequest.builder().commentText("   ").build();

    Set<ConstraintViolation<AddRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).hasSize(1);
    assertThat(violations.iterator().next().getMessage()).isEqualTo("Comment text cannot be blank");
  }

  @Test
  @DisplayName("Long comment is valid")
  @Tag("standard-processing")
  void longCommentIsValid() {
    String longComment = "A".repeat(2000); // 2000 character comment
    AddRecipeCommentRequest request =
        AddRecipeCommentRequest.builder().commentText(longComment).build();

    Set<ConstraintViolation<AddRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).isEmpty();
    assertThat(request.getCommentText()).hasSize(2000);
  }

  @Test
  @DisplayName("Special characters in comment are valid")
  @Tag("standard-processing")
  void specialCharactersInCommentAreValid() {
    AddRecipeCommentRequest request =
        AddRecipeCommentRequest.builder()
            .commentText("Comment with special chars: @#$%^&*()![]{}|\\:;\"'<>?")
            .build();

    Set<ConstraintViolation<AddRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).isEmpty();
  }
}
