package com.recipe_manager.model.dto.request;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Set;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class EditRecipeCommentRequestTest {

  private Validator validator;

  @BeforeEach
  void setUp() {
    ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
    validator = factory.getValidator();
  }

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    EditRecipeCommentRequest request = new EditRecipeCommentRequest("Updated comment");

    assertThat(request.getCommentText()).isEqualTo("Updated comment");
  }

  @Test
  @DisplayName("No-args constructor sets defaults and nulls")
  @Tag("standard-processing")
  void noArgsConstructorSetsDefaults() {
    EditRecipeCommentRequest request = new EditRecipeCommentRequest();

    assertThat(request.getCommentText()).isNull();
  }

  @Test
  @DisplayName("Builder sets fields correctly")
  @Tag("standard-processing")
  void builderSetsFieldsCorrectly() {
    EditRecipeCommentRequest request =
        EditRecipeCommentRequest.builder().commentText("New comment text").build();

    assertThat(request.getCommentText()).isEqualTo("New comment text");
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    EditRecipeCommentRequest request = new EditRecipeCommentRequest();

    request.setCommentText("Modified comment");
    assertThat(request.getCommentText()).isEqualTo("Modified comment");
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    EditRecipeCommentRequest request1 =
        EditRecipeCommentRequest.builder().commentText("Same comment").build();
    EditRecipeCommentRequest request2 =
        EditRecipeCommentRequest.builder().commentText("Same comment").build();

    assertThat(request1).isEqualTo(request2);
    assertThat(request1.hashCode()).isEqualTo(request2.hashCode());
    assertThat(request1.toString()).contains("Same comment");
  }

  @Test
  @DisplayName("Valid comment passes validation")
  @Tag("standard-processing")
  void validCommentPassesValidation() {
    EditRecipeCommentRequest request =
        EditRecipeCommentRequest.builder().commentText("This is a valid updated comment").build();

    Set<ConstraintViolation<EditRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).isEmpty();
  }

  @Test
  @DisplayName("Null comment fails validation")
  @Tag("error-processing")
  void nullCommentFailsValidation() {
    EditRecipeCommentRequest request = EditRecipeCommentRequest.builder().commentText(null).build();

    Set<ConstraintViolation<EditRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).hasSize(1);
    assertThat(violations.iterator().next().getMessage()).isEqualTo("Comment text cannot be blank");
  }

  @Test
  @DisplayName("Empty comment fails validation")
  @Tag("error-processing")
  void emptyCommentFailsValidation() {
    EditRecipeCommentRequest request = EditRecipeCommentRequest.builder().commentText("").build();

    Set<ConstraintViolation<EditRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).hasSize(1);
    assertThat(violations.iterator().next().getMessage()).isEqualTo("Comment text cannot be blank");
  }

  @Test
  @DisplayName("Blank comment fails validation")
  @Tag("error-processing")
  void blankCommentFailsValidation() {
    EditRecipeCommentRequest request =
        EditRecipeCommentRequest.builder().commentText("   ").build();

    Set<ConstraintViolation<EditRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).hasSize(1);
    assertThat(violations.iterator().next().getMessage()).isEqualTo("Comment text cannot be blank");
  }

  @Test
  @DisplayName("Long comment is valid")
  @Tag("standard-processing")
  void longCommentIsValid() {
    String longComment = "A".repeat(2000); // 2000 character comment
    EditRecipeCommentRequest request =
        EditRecipeCommentRequest.builder().commentText(longComment).build();

    Set<ConstraintViolation<EditRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).isEmpty();
    assertThat(request.getCommentText()).hasSize(2000);
  }

  @Test
  @DisplayName("Special characters in comment are valid")
  @Tag("standard-processing")
  void specialCharactersInCommentAreValid() {
    EditRecipeCommentRequest request =
        EditRecipeCommentRequest.builder()
            .commentText("Updated comment with special chars: @#$%^&*()![]{}|\\:;\"'<>?")
            .build();

    Set<ConstraintViolation<EditRecipeCommentRequest>> violations = validator.validate(request);

    assertThat(violations).isEmpty();
  }
}
