package com.recipe_manager.model.dto.recipe;

import static org.assertj.core.api.Assertions.assertThat;


import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class RecipeTagDtoTest {

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    RecipeTagDto dto = new RecipeTagDto(2L, "name");
    assertThat(dto.getTagId()).isEqualTo(2L);
    assertThat(dto.getName()).isEqualTo("name");
  }

  @Test
  @DisplayName("No-args constructor sets defaults and nulls")
  @Tag("standard-processing")
  void noArgsConstructorSetsDefaults() {
    RecipeTagDto dto = new RecipeTagDto();
    assertThat(dto.getName()).isNull();
    assertThat(dto.getTagId()).isNull();
  }

  @Test
  @DisplayName("Builder sets fields and uses defaults")
  @Tag("standard-processing")
  void builderSetsFieldsAndDefaults() {
    RecipeTagDto dto = RecipeTagDto.builder().name("T").build();
    assertThat(dto.getName()).isEqualTo("T");
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    RecipeTagDto dto = new RecipeTagDto();
    dto.setName("T");
    assertThat(dto.getName()).isEqualTo("T");

    dto.setTagId(100L);
    assertThat(dto.getTagId()).isEqualTo(100L);
  }

  @Test
  @DisplayName("Tag name handling works correctly")
  @Tag("standard-processing")
  void tagNameHandling() {
    RecipeTagDto dto = new RecipeTagDto();
    dto.setName("Breakfast");
    assertThat(dto.getName()).isEqualTo("Breakfast");
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    RecipeTagDto dto1 = RecipeTagDto.builder().name("A").build();
    RecipeTagDto dto2 = RecipeTagDto.builder().name("A").build();
    assertThat(dto1).isEqualTo(dto2);
    assertThat(dto1.hashCode()).isEqualTo(dto2.hashCode());
    assertThat(dto1.toString()).contains("A");
  }

  @Test
  @DisplayName("Null handling for all fields")
  @Tag("error-processing")
  void nullHandlingForAllFields() {
    RecipeTagDto dto = new RecipeTagDto(null, null);
    assertThat(dto.getTagId()).isNull();
    assertThat(dto.getName()).isNull();
  }
}
