### Ingredient Management - Get Recipe Ingredients
GET http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Ingredient Management - Get All Ingredients
GET http://recipe.local/api/v1/recipe-manager/recipe-management/ingredients
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Ingredient Management - Add Ingredient Comment
POST http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/456/comment
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Ingredient Management - Edit Ingredient Comment
PUT http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/456/comment
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Ingredient Management - Delete Ingredient Comment
DELETE http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/456/comment
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Ingredient Management - Add Ingredient Media
POST http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/456/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Ingredient Management - Update Ingredient Media
PUT http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/456/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Ingredient Management - Delete Ingredient Media
DELETE http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/456/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Ingredient Management - Scale Recipe Ingredients
GET http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/scale?quantity=2.5
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Ingredient Management - Generate Shopping List
GET http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/shopping-list
Content-Type: application/json
Authorization: Bearer {{accessToken}}
