### Media Management - Add Media to Recipe
POST http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Media Management - Update Media on Recipe
PUT http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Media Management - Delete Media from Recipe
DELETE http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Media Management - Add Media to Ingredient
POST http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/456/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Media Management - Update Media on Ingredient
PUT http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/456/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Media Management - Delete Media from Ingredient
DELETE http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/ingredients/456/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Media Management - Add Media to Step
POST http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps/789/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Media Management - Update Media on Step
PUT http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps/789/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Media Management - Delete Media from Step
DELETE http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps/789/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}
