### Step Management - Get Recipe Steps
GET http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Step Management - Add Step Comment
POST http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps/789/comment
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Step Management - Edit Step Comment
PUT http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps/789/comment
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Step Management - Delete Step Comment
DELETE http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps/789/comment
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Step Management - Add Step Media
POST http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps/789/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Step Management - Update Step Media
PUT http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps/789/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Step Management - Delete Step Media
DELETE http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/steps/789/media
Content-Type: application/json
Authorization: Bearer {{accessToken}}
