### Tag Management - Get Recipe Tags
GET http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/tags
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Tag Management - Add Tag to Recipe
POST http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/tags
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Tag Management - Remove Tag from Recipe
DELETE http://recipe.local/api/v1/recipe-manager/recipe-management/recipes/123/tags
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Tag Management - Get All Tags
GET http://recipe.local/api/v1/recipe-manager/recipe-management/tags
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Tag Management - Get Popular Tags
GET http://recipe.local/api/v1/recipe-manager/recipe-management/tags/popular
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

### Tag Management - Search Tags
GET http://recipe.local/api/v1/recipe-manager/recipe-management/tags/search?query=pasta
Content-Type: application/json
Authorization: Bearer {{accessToken}}
