package com.recipe_manager.model.dto.collection;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class CollectionTagDtoTest {

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    CollectionTagDto dto = new CollectionTagDto(1L, "dessert");

    assertThat(dto.getTagId()).isEqualTo(1L);
    assertThat(dto.getName()).isEqualTo("dessert");
  }

  @Test
  @DisplayName("No-args constructor sets nulls")
  @Tag("standard-processing")
  void noArgsConstructorSetsDefaults() {
    CollectionTagDto dto = new CollectionTagDto();

    assertThat(dto.getTagId()).isNull();
    assertThat(dto.getName()).isNull();
  }

  @Test
  @DisplayName("Builder sets fields correctly")
  @Tag("standard-processing")
  void builderSetsFields() {
    CollectionTagDto dto = CollectionTagDto.builder()
        .tagId(2L)
        .name("quick-meals")
        .build();

    assertThat(dto.getTagId()).isEqualTo(2L);
    assertThat(dto.getName()).isEqualTo("quick-meals");
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    CollectionTagDto dto = new CollectionTagDto();

    dto.setTagId(3L);
    assertThat(dto.getTagId()).isEqualTo(3L);

    dto.setName("favorites");
    assertThat(dto.getName()).isEqualTo("favorites");
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    CollectionTagDto dto1 = CollectionTagDto.builder()
        .tagId(1L)
        .name("dinner")
        .build();
    CollectionTagDto dto2 = CollectionTagDto.builder()
        .tagId(1L)
        .name("dinner")
        .build();

    assertThat(dto1).isEqualTo(dto2);
    assertThat(dto1.hashCode()).isEqualTo(dto2.hashCode());
    assertThat(dto1.toString()).contains("tagId=1");
    assertThat(dto1.toString()).contains("name=dinner");
  }

  @Test
  @DisplayName("Null handling for name field")
  @Tag("error-processing")
  void nullHandlingForName() {
    CollectionTagDto dto = CollectionTagDto.builder()
        .tagId(1L)
        .name(null)
        .build();

    assertThat(dto.getTagId()).isEqualTo(1L);
    assertThat(dto.getName()).isNull();
  }

  @Test
  @DisplayName("Null handling for tagId field")
  @Tag("error-processing")
  void nullHandlingForTagId() {
    CollectionTagDto dto = CollectionTagDto.builder()
        .tagId(null)
        .name("breakfast")
        .build();

    assertThat(dto.getTagId()).isNull();
    assertThat(dto.getName()).isEqualTo("breakfast");
  }

  @Test
  @DisplayName("Different names result in non-equal DTOs")
  @Tag("standard-processing")
  void differentNamesAreNotEqual() {
    CollectionTagDto dto1 = CollectionTagDto.builder().tagId(1L).name("lunch").build();
    CollectionTagDto dto2 = CollectionTagDto.builder().tagId(1L).name("brunch").build();

    assertThat(dto1).isNotEqualTo(dto2);
  }

  @Test
  @DisplayName("Different tagIds result in non-equal DTOs")
  @Tag("standard-processing")
  void differentTagIdsAreNotEqual() {
    CollectionTagDto dto1 = CollectionTagDto.builder().tagId(1L).name("dinner").build();
    CollectionTagDto dto2 = CollectionTagDto.builder().tagId(2L).name("dinner").build();

    assertThat(dto1).isNotEqualTo(dto2);
  }
}
