package com.recipe_manager.model.dto.collection;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDateTime;
import java.util.UUID;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("unit")
class CollectionFavoriteDtoTest {

  @Test
  @DisplayName("All-args constructor assigns all fields")
  @Tag("standard-processing")
  void allArgsConstructorAssignsFields() {
    UUID userId = UUID.randomUUID();
    LocalDateTime now = LocalDateTime.now();
    CollectionFavoriteDto dto = new CollectionFavoriteDto(1L, userId, now);
    assertThat(dto.getCollectionId()).isEqualTo(1L);
    assertThat(dto.getUserId()).isEqualTo(userId);
    assertThat(dto.getFavoritedAt()).isEqualTo(now);
  }

  @Test
  @DisplayName("No-args constructor sets defaults and nulls")
  @Tag("standard-processing")
  void noArgsConstructorSetsDefaults() {
    CollectionFavoriteDto dto = new CollectionFavoriteDto();
    assertThat(dto.getUserId()).isNull();
    assertThat(dto.getCollectionId()).isNull();
    assertThat(dto.getFavoritedAt()).isNull();
  }

  @Test
  @DisplayName("Builder sets fields and uses defaults")
  @Tag("standard-processing")
  void builderSetsFieldsAndDefaults() {
    CollectionFavoriteDto dto =
        CollectionFavoriteDto.builder().favoritedAt(LocalDateTime.now()).build();
    assertThat(dto.getFavoritedAt()).isNotNull();
  }

  @Test
  @DisplayName("Setters and getters work for all fields")
  @Tag("standard-processing")
  void settersAndGettersWork() {
    CollectionFavoriteDto dto = new CollectionFavoriteDto();
    UUID userId = UUID.randomUUID();
    dto.setUserId(userId);
    assertThat(dto.getUserId()).isEqualTo(userId);

    Long collectionId = 123L;
    dto.setCollectionId(collectionId);
    assertThat(dto.getCollectionId()).isEqualTo(collectionId);
  }

  @Test
  @DisplayName("Timestamp handling works correctly")
  @Tag("standard-processing")
  void timestampHandling() {
    LocalDateTime now = LocalDateTime.now();
    CollectionFavoriteDto dto = new CollectionFavoriteDto();
    dto.setFavoritedAt(now);
    assertThat(dto.getFavoritedAt()).isEqualTo(now);
  }

  @Test
  @DisplayName("Equals/hashCode/toString are generated by Lombok")
  @Tag("standard-processing")
  void equalsHashCodeToString() {
    CollectionFavoriteDto dto1 =
        CollectionFavoriteDto.builder().favoritedAt(LocalDateTime.now()).build();
    CollectionFavoriteDto dto2 =
        CollectionFavoriteDto.builder().favoritedAt(dto1.getFavoritedAt()).build();
    assertThat(dto1).isEqualTo(dto2);
    assertThat(dto1.hashCode()).isEqualTo(dto2.hashCode());
    assertThat(dto1.toString()).contains("favoritedAt");
  }

  @Test
  @DisplayName("Null handling for all fields")
  @Tag("error-processing")
  void nullHandlingForAllFields() {
    CollectionFavoriteDto dto = CollectionFavoriteDto.builder().build();
    assertThat(dto.getCollectionId()).isNull();
    assertThat(dto.getUserId()).isNull();
    assertThat(dto.getFavoritedAt()).isNull();
  }
}
