---
name: Link Checker

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main, develop]
    paths:
      - '**.md'
      - 'docs/**'
  schedule:
    # Run weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  link-check:
    name: Check Broken Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check links in markdown files
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Check all markdown files
          args: |
            --verbose
            --no-progress
            --exclude-mail
            --exclude 'localhost'
            --exclude '127.0.0.1'
            --exclude-path '.github/ISSUE_TEMPLATE'
            '**/*.md'
          # Only fail on errors, not warnings
          fail: true
          # Output file
          output: lychee-report.md

      - name: Generate link report summary
        if: always()
        run: |
          if [ -f lychee-report.md ]; then
            echo "## 🔗 Link Check Report" > link-summary.md
            echo "" >> link-summary.md
            cat lychee-report.md >> link-summary.md
          else
            echo "✅ No broken links found!" > link-summary.md
          fi

      - name: Upload link report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: link-check-report
          path: link-summary.md
          retention-days: 30

      - name: Comment on PR
        if: github.event_name == 'pull_request' && failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: links
          message: |
            ## 🔗 Broken Links Detected

            ❌ This PR introduces broken or invalid links in documentation.

            <details>
            <summary>View link check report</summary>

            $(cat link-summary.md)

            </details>

            Please fix the broken links before merging.

      - name: Comment success on PR
        if: github.event_name == 'pull_request' && success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: links
          message: |
            ## 🔗 Link Check Passed

            ✅ All links in documentation are valid!
